openapi: 3.0.0
info:
  title: Impersonate Management API
  version: 1.0.0
paths:
  /:
    post:
      summary: Impersonate a user
      operationId: create_impersonate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_uuid:
                  type: string
                  format: uuid
              required:
                - user_uuid
      responses:
        "200":
          description: Successfully generate impersonate tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
components:
  schemas:
    SuccessResponse:
      x-go-optional-value: true
      type: object
      properties:
        result:
          type: string
