openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: User login successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
        "400":
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Username/Password is wrong"
  /password/reset/init:
    post:
      summary: Initiate password reset using username
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordResetInit"
      responses:
        "200":
          description: Password reset initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
  /password/reset:
    post:
      summary: Reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordReset"
      responses:
        "200":
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /logout:
    post:
      summary: Logout user
      responses:
        "200":
          description: Logout successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
  /email/verify:
    post:
      summary: Verify email address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailVerifyRequest'
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /token/refresh:
    post:
      summary: Refresh JWT tokens
      responses:
        '200':
          description: Tokens refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /mobile/login:
    post:
      summary: Mobile login endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Mobile login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT access token
                  refreshToken:
                    type: string
                    description: JWT refresh token
                required:
                  - accessToken
                  - refreshToken
  /username/find:
    post:
      summary: Send username to user's email address
      description: If an account exists with the provided email, the username will be sent to that email address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FindUsernameRequest"
      responses:
        "200":
          description: Request processed successfully. If an account exists, an email with the username will be sent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the request was processed
                    example: "If an account exists with that email, we will send the username to it."
components:
  schemas:
    Login:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
        user:
          $ref: "#/components/schemas/User"
      required:
        - status
        - message
        - user
    User:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        email:
          type: string
      required:
        - uuid
        - name
        - email
    PasswordReset:
      type: object
      properties:
        code:
          type: string
        password:
          type: string
      required:
        - code
        - password
    RegisterRequest:
      type: object
      properties:
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john.doe@example.com
        password:
          type: string
      required:
        - name
        - email
        - password
    EmailVerifyRequest:
      type: object
      properties:
        email:
          type: string
      required:
        - email
    PasswordResetInit:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          description: Username of the account to reset password for
    Tokens:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken
        - refreshToken
    FindUsernameRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          description: Email address to find username for
