openapi: 3.0.0
info:
  title: Impersonate Management API
  version: 1.0.0
paths:
  /enable:
    post:
      summary: Enable an existing 2FA method
      operationId: post_2fa_enable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "200":
          description: 2FA method enabled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error

  /disable:
    post:
      summary: Disable an existing 2FA method
      operationId: post_2fa_disable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "200":
          description: 2FA method disabled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error
  /:
    post:
      summary: Create a new 2FA method
      operationId: post_2fa_create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "201":
          description: 2FA method created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "409":
          description: 2FA method already exists
        "500":
          description: Internal server error
  /delete:
    post:
      summary: Delete a 2FA method
      operationId: delete_2fa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "200":
          description: 2FA method deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error
components:
  schemas:
    SuccessResponse:
      x-go-optional-value: true
      type: object
      properties:
        result:
          type: string