openapi: 3.0.0
info:
  title: Impersonate Management API
  version: 1.0.0
paths:
  /send:
    post:
      summary: Initiate sending 2fa code
      operationId: post_2fa_send
      requestBody:
        x-go-optional-value: true
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twofa_type:
                  type: string
                delivery_option:
                  type: string
                user_id:
                  type: string
                  format: uuid
              required:
                - twofa_type
                - delivery_option
                - user_id
      responses:
        "200":
          description: 2fa initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /validate:
    post:
      summary: Authenticate 2fa passcode
      operationId: post_2fa_validate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twofa_type:
                  type: string
                passcode:
                  type: string
              required:
                - passcode
                - twofa_type
      responses:
        "200":
          description: 2fa validated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "202":
          description: 2FA successful but select user required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SelectUserRequiredResponse"
  /enable:
    post:
      summary: Enable an existing 2FA method
      operationId: post_2fa_enable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "200":
          description: 2FA method enabled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error

  /disable:
    post:
      summary: Disable an existing 2FA method
      operationId: post_2fa_disable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "200":
          description: 2FA method disabled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error
  /:
    post:
      summary: Create a new 2FA method
      operationId: post_2fa_create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "201":
          description: 2FA method created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "409":
          description: 2FA method already exists
        "500":
          description: Internal server error
  /delete:
    post:
      summary: Delete a 2FA method
      operationId: delete_2fa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  format: uuid
                twofa_id:
                  type: string
                  format: uuid
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - login_id
                - twofa_type
      responses:
        "200":
          description: 2FA method deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error
components:
  schemas:
    SuccessResponse:
      x-go-optional-value: true
      type: object
      properties:
        result:
          type: string
    SelectUserRequiredResponse:
      x-go-optional-value: true
      type: object
      properties:
        status:
          type: string
          example: "select_user_required"
        message:
          type: string
          example: "Select user required"
        temp_token:
          type: string
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
    Login:
      x-go-optional-value: true
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
          example: "2FA verification successful"
        users:
          type: array
          description: List of users associated with the login. Usually contains one user, but may contain multiple if same username is shared.
          items:
            $ref: "#/components/schemas/User"
        status:
          type: string
          example: success
        message:
          type: string
        user:
          $ref: "#/components/schemas/User"
        requires2FA:
          type: boolean
          description: Whether 2FA verification is required
        loginToken:
          type: string
          description: Token for 2FA verification if required
      required:
        - status
        - message
        - user
