openapi: 3.0.0
info:
  title: Role Management API
  version: 1.0.0
servers:
  - url: /api/v1
    description: Base API path
paths:
  /:
    get:
      summary: Get a list of roles
      responses:
        "200":
          description: List of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      format: uuid
                    name:
                      type: string
                      description: Role name
    post:
      summary: Create a new role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Role name
      responses:
        "201":
          description: Role created
  /{uuid}:
    get:
      summary: Get a role by UUID
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Role details
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: uuid
                  name:
                    type: string
                    description: Role name
        "404":
          description: Role not found
    put:
      summary: Update an existing role
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Role name
      responses:
        "200":
          description: Role updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: uuid
                  name:
                    type: string
                    description: Role name
    delete:
      summary: Delete a role
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Role deleted
        "404":
          description: Role not found
