openapi: 3.0.0
info:
  title: Role Management API
  version: 1.0.0
paths:
  /roles:
    get:
      summary: Get a list of roles
      responses:
        "200":
          description: List of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      format: uuid
                    name:
                      type: string
                      description: Role name
